### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by default-kramer** [AlexKnauth/scribble-code-examples#11]
I noticed that this repository doesn't have a license. Can I have your permission to include a project-specific fork of scribble-code-examples in my "plisqin" repository? Or, can you add a license that would answer that question for me?

Thanks for your attention.

**Comment by AlexKnauth** [comment]
https://github.com/AlexKnauth/scribble-code-examples/commit/42f7cd362bd6c009d244cbc5dcfecc8d2dab3849
